name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: build mod
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: save mod file
        uses: actions/upload-artifact@v3
        with:
          name: BeastRender-JAR
          path: build/libs/*.jar
